name: hmp_pro
description: HMP PRO - Industrial Light Weight Deflectometer
publish_to: 'none'
version: 3.4.0+27
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.5
  fl_chart: ^0.68.0
  csv: ^5.1.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  share_plus: ^10.0.2
  pdf: ^3.11.1
  http: ^1.2.2
  battery_plus: ^6.0.1
  image_picker: ^1.1.2
  flutter_tts: ^4.0.2
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: "#0A0E1A"
  adaptive_icon_foreground: "assets/icon/logo.png"