name: hmp_pro
description: HMP PRO - Industrial Light Weight Deflectometer
publish_to: 'none'
version: 3.5.0+30

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Bluetooth
  flutter_blue_plus: ^1.35.5

  # Charts
  fl_chart: ^0.68.0

  # CSV & Reports
  csv: ^5.1.1
  pdf: ^3.11.1

  # Formatting
  intl: ^0.19.0

  # Storage
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4

  # Permissions & Location
  permission_handler: ^11.3.1
  geolocator: ^12.0.0

  # Sharing
  share_plus: ^10.0.2

  # Networking
  http: ^1.2.2

  # Device Info
  battery_plus: ^6.0.1

  # Camera / Images
  image_picker: ^1.1.2

  # Text-to-speech
  flutter_tts: ^4.0.2

  # Keep screen awake
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/logo_v3.png"
  adaptive_icon_background: "#F5F7FA"
  adaptive_icon_foreground: "assets/icon/logo_v3.png"